### ISSUE TITLE
Large arrays don't move from Javascript to the SoS kernel

### ISSUE THREAD

**Issue by poldap** [vatlab/sos-javascript#7]
Thank you for the great work. We've been using SoS to teach image processing laboratory sessions with JupyterLab, and it has been a life-saver. 

We are in the progress of updating our JupyterLab hub from v1 to v2. Currently, our production machines are in `1.2.18` and the staging platform is in `2.2.9`. Both have the iJavascript kernel installed (`5.2.0`) and SoS working well between SoS and Javascript. **However**, for some reason I can not understand, in JupyterLab v2 JavaScript arrays seem to move to the SoS kernel only if they contain less than **2220** elements (see screenshots below). 

A bit more information on the SoS packages in each machine. 

Production machine (JupyterLab v1, everything working well)
```
sos==0.21.12
sos-bash==0.20.0
sos-javascript==0.18.1
sos-julia==0.18.5
sos-matlab==0.18.4
sos-notebook==0.21.12
sos-papermill==0.2.0
sos-python==0.18.4
sos-r==0.19.6
```

Staging machine (JupyterLab v2, weird limit in size of JS array)
``` 
sos==0.22.5
sos-bash==0.20.0
sos-javascript==0.18.1
sos-julia==0.18.5
sos-matlab==0.18.5
sos-notebook==0.22.4
sos-papermill==0.2.1
sos-python==0.18.4
sos-r==0.19.6
```

<img width="1655" alt="2219" src="https://user-images.githubusercontent.com/7040555/118613592-2efe8200-b7bf-11eb-826f-5f887109087d.png">
<img width="1655" alt="2220" src="https://user-images.githubusercontent.com/7040555/118613601-30c84580-b7bf-11eb-9b98-53c2c5ab4eb7.png">

**Comment by BoPeng** [comment]
Appears to be working here...

![image](https://user-images.githubusercontent.com/9889312/118716284-456e0300-b7ea-11eb-8384-3bc21245c8fd.png)

This works for both classical and jupyterlab interface, and

```
pip list | grep sos
jupyterlab-sos                0.8.1
sos                           0.22.4  
sos-javascript                0.18.1
sos-notebook                  0.22.4
sos-python                    0.18.4
sos-r                         0.19.6
```

**Comment by BoPeng** [comment]
@poldap However,  checking the code I found that maybe for whatever reason your `execute_result`was sent in multiple batches. I have submitted a patch to handle this situation. Could you please check if the master branch works ok for you?

**Comment by poldap** [comment]
Great, thank you! I will get back to you as soon as I can try it out (I don't administer the JupyterLab servers myself).

**Comment by nibheis** [comment]
Hi @BoPeng,

I installed git+https://github.com/vatlab/sos-javascript.git@226cf8c4425ba650e0237b3045d66262a8a5d709 with your fix (I checked that) for @poldap, but unfortunaltely this does not change the error we are getting.

I also verified: the conversion fails because the json string hits a maximum size of exactly 10000 characters - if that indicates anything.

Could this limit come from other python packages of the jupyter stack (like 'notebook') ?

**Comment by BoPeng** [comment]
That is what confused me. As I have said, I tested much larger arrays but could not reproduce the error. My patch was based on the assumption that the complete string was sent through multiple messages, but that does not appear to be the case.

Unlike other kernels for which functions were developed to convert different types, the javascript module is very easy. 

https://github.com/vatlab/sos-javascript/blob/2a2e49f0bad8c4e5a31789f920f74919d9ded898/src/sos_javascript/kernel.py#L70-L71

So when you have

```
%get trial --from JavaScript
```

```
JSON.stringify({ 'trial': trial })
```
is executed in the JavaScript kernel, and sos simply catches the output (as `execute_result`) and load into Python.

What you can do is to 

1. first check if you can see the complete expression in the output of `JSON.stringify({ 'trial': trial })`
2. then add `%capture` and see if sos could capture all of the output 
3. then we can see why `sos-javascript` failed to capture all output.

**Comment by BoPeng** [comment]
Here is what happens when I try it on the public sos jupyterhub server sosworkflows.com (for some reason I needed to refresh the page twice to get the kernels loaded), and the following shows exactly what `sos-javascript` has done to get the array in the SoS kernel. I am curious as at which step things went wrong on your side.

![image](https://user-images.githubusercontent.com/9889312/118763292-32385300-b83d-11eb-9845-9b0fb8fdb06c.png)
![image](https://user-images.githubusercontent.com/9889312/118763305-39f7f780-b83d-11eb-8176-f349d468768c.png)
![image](https://user-images.githubusercontent.com/9889312/118763356-52681200-b83d-11eb-809c-cdd95c45131e.png)
![image](https://user-images.githubusercontent.com/9889312/118763469-8c391880-b83d-11eb-9c8c-de8ca972c03b.png)

At this point I think maybe you have an old version of some third-party components...

**Comment by nibheis** [comment]
Thanks. I will try to update some of the components then...

**Comment by nibheis** [comment]
FYI: I just checked on our production platform (still running jupyterlab 1.x) and it works...
So, this fails on our staging platform which is a major update from production :-(

**Comment by nibheis** [comment]
I modified kernel.py to debug the issue. I added : `return({ "trial": expr })` to see the raw string, here is the result:

```
'\'{"trial":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
[...]
2212,2213,2214,2215,2216,2217,2218,2219,\'... 151 more characters'
```

Yes, the string the js kernel tries to 'put_vars()' on actually contains '... 151 more characters'

**Comment by BoPeng** [comment]
What is the command in js kernel to print the jsonified string to stdout? I  can try to capture from stdout instead of execute_result. You can try these with the capture magic I showed.

**Comment by nibheis** [comment]
I have tried to use `'process.stdout.write(JSON.stringify({{ {} }}))'`.
It kind of works, since when I use this I don't get anything in the 'execute_result'.

I tried to get the 'stdout' and 'stderr' outputs from the get_response() call, but I still only get data in execute_result.
How should I get stdout ?

**Comment by nibheis** [comment]
found 'stdout' in 'stream' :-)

**Comment by poldap** [comment]
@BoPeng @nibheis thank you for continuing the discussion. 

The `%capture` magic works if I wrap `JSON.stringify({'trial': trial}))` with `console.log()`. May it be that the differences are in our iJavaScript kernels and their output objects? 

<img width="1167" alt="Screenshot 2021-05-19 at 09 28 14" src="https://user-images.githubusercontent.com/7040555/118772991-a5b18300-b884-11eb-8d36-a64d52f650fe.png">

<img width="1167" alt="Screenshot 2021-05-19 at 09 28 30" src="https://user-images.githubusercontent.com/7040555/118772927-95010d00-b884-11eb-91a0-335ea7a13230.png">

**Comment by nibheis** [comment]
Yes @poldap , I think our JavaScript kernel truncates the outputs. I could not reproduce that with strings, but with large arrays the output are certainly truncated.

I'm in the process of using 'stdout' instead of 'execute_result' for passing variable from JS to SoS.

**Comment by nibheis** [comment]
Here is a version of `put_vars()` that uses `stdout` instead of `execute_result` :

```
    def put_vars(self, items, to_kernel=None):
        # first let us get all variables with names starting with sos
        if not items:
            return {}

        py_repr = 'process.stdout.write(JSON.stringify({{ {} }}))'.format(','.join(
            '"{0}":{0}'.format(x) for x in items))

        expr = ''
        response = self.sos_kernel.get_response(py_repr, ('stream'))
        for msg_type in response:
            if msg_type[0] == 'stream':
                stream = msg_type[1]
                if stream['name'] == 'stdout':
                    expr = stream['text']

        try:
            return(json.loads(expr))
        except Exception as e:
            self.sos_kernel.warn(
                'Failed to convert {} to Python object: {}'.format(expr, e))
            return {}
```

It works:
![image](https://user-images.githubusercontent.com/52066010/118775777-d094da80-b876-11eb-9e83-6c10767b8b80.png)

Now, @BoPeng, do you think we should use this in sos_javascript so that it works with all javascript kernels, or should we try to "fix" the javascript kernel we use ?

**Comment by poldap** [comment]
It seems that fixing `put_vars()` is the way to go: our staging platform seems to use a more modern JS version. However, I could not verify that was the cause of the difference.

On our staging platform, `console.log(process.versions)` says
```
{
  node: '15.14.0',
  v8: '8.6.395.17-node.28',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k+quic',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
while in sosworkflows.com I get 
``` 
{
  node: '12.4.0',
  v8: '7.4.288.27-node.18',
  uv: '1.29.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.38.0',
  napi: '4',
  llhttp: '1.1.3',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
```

**Comment by BoPeng** [comment]
Thank you all for investigating this. I will switch to stdout and make a new release.

**Comment by BoPeng** [comment]
sos-javascript 0.18.2 is now on pypi.
